#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Destination2.WebUi.Search;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/SearchForm.cshtml")]
    public partial class _Views_Partials_SearchForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Partials_SearchForm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Partials\SearchForm.cshtml"
 using (Html.BeginForm("ProcessSearchFormInput", "Search", new { area = "Search" }, FormMethod.Post, new { onkeypress = "return event.keyCode != 13;" }))
{

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    This is the search form\r\n    <button type = \"submit\" title=\"Search\">Se" +
"arch</button>\r\n </div>\r\n");

            
            #line 7 "..\..\Views\Partials\SearchForm.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
