#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Destination2.WebUi.PackageSearch;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Wait/FlightWait.cshtml")]
    public partial class _Views_Wait_FlightWait_cshtml : System.Web.Mvc.WebViewPage<Destination2.WebUi.PackageSearch.Models.FlightWaitViewModel>
    {
        public _Views_Wait_FlightWait_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Wait\FlightWait.cshtml"
  
    ViewBag.Title = "FlightWait";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>This is the package wait page</h2>\r\n<p>There is going to be some fancy pa" +
"ge here prob scrolling through differnet images</p>\r\n\r\n");

DefineSection("Javascript", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            $.ajax({\r\n               " +
" url: \'/Search/Package-Flight-Start\',\r\n                type: \'POST\',\r\n          " +
"      data: \"{id: ");

            
            #line 17 "..\..\Views\Wait\FlightWait.cshtml"
                       Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(@"}"",
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    alert(data.success);
                },
                error: function () {
                    alert(""error"");
                }
            });
        });
    </script>
");

});

WriteLiteral("\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
