//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destination2.WebUi.Search.ServiceFlights {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightSearch", Namespace="http://schemas.datacontract.org/2004/07/Destination2.Services.Flights.Entities")]
    [System.SerializableAttribute()]
    public partial class FlightSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CabinClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartureAirportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinationAirportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DirectFlightsOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfAdultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfInfantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CabinClassID {
            get {
                return this.CabinClassIDField;
            }
            set {
                if ((this.CabinClassIDField.Equals(value) != true)) {
                    this.CabinClassIDField = value;
                    this.RaisePropertyChanged("CabinClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartureAirportID {
            get {
                return this.DepartureAirportIDField;
            }
            set {
                if ((this.DepartureAirportIDField.Equals(value) != true)) {
                    this.DepartureAirportIDField = value;
                    this.RaisePropertyChanged("DepartureAirportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinationAirportID {
            get {
                return this.DestinationAirportIDField;
            }
            set {
                if ((this.DestinationAirportIDField.Equals(value) != true)) {
                    this.DestinationAirportIDField = value;
                    this.RaisePropertyChanged("DestinationAirportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DirectFlightsOnly {
            get {
                return this.DirectFlightsOnlyField;
            }
            set {
                if ((this.DirectFlightsOnlyField.Equals(value) != true)) {
                    this.DirectFlightsOnlyField = value;
                    this.RaisePropertyChanged("DirectFlightsOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPackage {
            get {
                return this.IsPackageField;
            }
            set {
                if ((this.IsPackageField.Equals(value) != true)) {
                    this.IsPackageField = value;
                    this.RaisePropertyChanged("IsPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfAdults {
            get {
                return this.NumberOfAdultsField;
            }
            set {
                if ((this.NumberOfAdultsField.Equals(value) != true)) {
                    this.NumberOfAdultsField = value;
                    this.RaisePropertyChanged("NumberOfAdults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfChildren {
            get {
                return this.NumberOfChildrenField;
            }
            set {
                if ((this.NumberOfChildrenField.Equals(value) != true)) {
                    this.NumberOfChildrenField = value;
                    this.RaisePropertyChanged("NumberOfChildren");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfInfants {
            get {
                return this.NumberOfInfantsField;
            }
            set {
                if ((this.NumberOfInfantsField.Equals(value) != true)) {
                    this.NumberOfInfantsField = value;
                    this.RaisePropertyChanged("NumberOfInfants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTypeField, value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightSearchResult", Namespace="http://schemas.datacontract.org/2004/07/Destination2.Services.Flights.Entities")]
    [System.SerializableAttribute()]
    public partial class FlightSearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Destination2.WebUi.Search.ServiceFlights.FlightSearch FlightSearchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlightSearchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Destination2.WebUi.Search.ServiceFlights.FlightSearch FlightSearch {
            get {
                return this.FlightSearchField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightSearchField, value) != true)) {
                    this.FlightSearchField = value;
                    this.RaisePropertyChanged("FlightSearch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlightSearchId {
            get {
                return this.FlightSearchIdField;
            }
            set {
                if ((this.FlightSearchIdField.Equals(value) != true)) {
                    this.FlightSearchIdField = value;
                    this.RaisePropertyChanged("FlightSearchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFlights.IFlightService")]
    public interface IFlightService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/StartSearch", ReplyAction="http://tempuri.org/IFlightService/StartSearchResponse")]
        Destination2.WebUi.Search.ServiceFlights.FlightSearchResult StartSearch(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/StartSearch", ReplyAction="http://tempuri.org/IFlightService/StartSearchResponse")]
        System.Threading.Tasks.Task<Destination2.WebUi.Search.ServiceFlights.FlightSearchResult> StartSearchAsync(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/RetriveSearch", ReplyAction="http://tempuri.org/IFlightService/RetriveSearchResponse")]
        Destination2.WebUi.Search.ServiceFlights.FlightSearch RetriveSearch(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/RetriveSearch", ReplyAction="http://tempuri.org/IFlightService/RetriveSearchResponse")]
        System.Threading.Tasks.Task<Destination2.WebUi.Search.ServiceFlights.FlightSearch> RetriveSearchAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/PerformSearch", ReplyAction="http://tempuri.org/IFlightService/PerformSearchResponse")]
        Destination2.WebUi.Search.ServiceFlights.FlightSearchResult PerformSearch(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/PerformSearch", ReplyAction="http://tempuri.org/IFlightService/PerformSearchResponse")]
        System.Threading.Tasks.Task<Destination2.WebUi.Search.ServiceFlights.FlightSearchResult> PerformSearchAsync(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlightServiceChannel : Destination2.WebUi.Search.ServiceFlights.IFlightService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightServiceClient : System.ServiceModel.ClientBase<Destination2.WebUi.Search.ServiceFlights.IFlightService>, Destination2.WebUi.Search.ServiceFlights.IFlightService {
        
        public FlightServiceClient() {
        }
        
        public FlightServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Destination2.WebUi.Search.ServiceFlights.FlightSearchResult StartSearch(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch) {
            return base.Channel.StartSearch(flightSearch);
        }
        
        public System.Threading.Tasks.Task<Destination2.WebUi.Search.ServiceFlights.FlightSearchResult> StartSearchAsync(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch) {
            return base.Channel.StartSearchAsync(flightSearch);
        }
        
        public Destination2.WebUi.Search.ServiceFlights.FlightSearch RetriveSearch(int id) {
            return base.Channel.RetriveSearch(id);
        }
        
        public System.Threading.Tasks.Task<Destination2.WebUi.Search.ServiceFlights.FlightSearch> RetriveSearchAsync(int id) {
            return base.Channel.RetriveSearchAsync(id);
        }
        
        public Destination2.WebUi.Search.ServiceFlights.FlightSearchResult PerformSearch(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch, int id) {
            return base.Channel.PerformSearch(flightSearch, id);
        }
        
        public System.Threading.Tasks.Task<Destination2.WebUi.Search.ServiceFlights.FlightSearchResult> PerformSearchAsync(Destination2.WebUi.Search.ServiceFlights.FlightSearch flightSearch, int id) {
            return base.Channel.PerformSearchAsync(flightSearch, id);
        }
    }
}
